import React from "react";
import Hero from "@/components/sections/hero";
import CTA from "@/components/sections/cta";
import { Footer } from "@/components/layout/footer";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <React.Fragment>
      <main className="bg-[#FAxFCFF] bg-[#F5F7FA] space-y-6 overflow-hidden min-h-screen">
        <Hero />
        {/* We will add other sections like Problem, HowItWorks, Features here later */}
        <CTA />
        <Footer />
      </main>
    </React.Fragment>
  );
}
